### ISSUE TITLE
Imports/Exports transpile only 1 per file

### ISSUE THREAD

**Issue by ghost** [frol/bos-component-ts-starter#6]
Imports/Exports per file transpile only 1, check screenshots
Before build:
<img width="527" alt="image" src="https://github.com/frol/bos-component-ts-starter/assets/155112125/1629c04f-303b-4f93-bc72-f80bb6f6e7e3">
After:
<img width="487" alt="image" src="https://github.com/frol/bos-component-ts-starter/assets/155112125/c09fc28f-e1aa-4922-8c37-e65848a794f1">

The same if we do export, if you do export from the file, only 1 function will transpile, and the others will left with export and this will break the code

**Comment by frol** [comment]
Resolved by #11
